---
- name: Configure SSH and create user on Debian 12
  hosts: all
  become: yes

  vars:
    ssh_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDDW1sg+ys6EEZd6ZzbDlrMMybOBUALEtERY2/ZKsvgbcAzTERxbtsqu+iNNDBo+sf3L3YuWkd8fLH4SJ3MQV42ySc6ml2tMT0G2r+QIWwFz+nPaD2DY8blgFpsa41TZxwKgLmqEtUVlps9Q6Un5KtJMjTl2MWYKswdxSqHw8em0DNigJolWfzsmoTvd1HXTYdj/PiJECW3nS38PFlL19Av6ipwrbxme2/VyvjolX5F3p/dgLkuUU7UMQ+tlx9gAlN0F/Tf6zMHSubIBC7lOf58zP+IlykdD4leVaNpFckk9hxnKCZpyM7jlwi2YSnYLAOh4v56NTq7c/yG2jX9+lSb"
    new_user: brickdev
    new_password: pass

  tasks:
    - name: Ensure openssh-server is installed
      apt:
        name: openssh-server
        state: present
        update_cache: yes

    - name: Create user brickdev
      user:
        name: "{{ new_user }}"
        password: "{{ 'pass' | password_hash('sha512') }}"
        shell: /bin/bash
        state: present
        create_home: yes

    - name: Copy SSH public key for brickdev
      authorized_key:
        user: "{{ new_user }}"
        key: "{{ ssh_key }}"
        state: present

    - name: Configure SSH to allow key-based authentication only
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        state: present
      loop:
        - { regexp: '^#?PermitRootLogin', line: 'PermitRootLogin no' }
        - { regexp: '^#?PasswordAuthentication', line: 'PasswordAuthentication no' }
        - { regexp: '^#?ChallengeResponseAuthentication', line: 'ChallengeResponseAuthentication no' }

    - name: Restart SSH service
      service:
        name: ssh
        state: restarted